[MASTERDIET-60] Login form adjustment
master-diet/master-diet-frontend pull request #24
Opened 2020-10-22 18:40 UTC by jakubowiczish

2020-10-23 21:40 UTC, jfoder requested changes

2020-10-23 21:40 UTC, jfoder commented on src/user/login/LoginSignupContainer.js
> +        // this.props.history.push('/')
Should be removed

2020-10-23 21:40 UTC, jfoder commented on src/user/login/LoginSignupContainer.js
> +              <input type="password"
Can we add some borders to these inputs?

2020-10-24 12:59 UTC, jakubowiczish commented on src/user/login/LoginSignupContainer.js
> +        // this.props.history.push('/')
Fixed

2020-10-24 12:59 UTC, jakubowiczish commented on src/user/login/LoginSignupContainer.js
> +              <input type="password"
Fixed

2020-10-24 14:12 UTC, jfoder approved these changes

2020-10-24 14:13 UTC, merged